### PR TITLE
git suggestions for the Blockstack Tutorial

### PR DESCRIPTION
**Pull request by nickycutesc**
Just some simple git problems I ran into and their solutions when going through the tutorial.

### CODE REVIEW

**Comment by moxiegirl** [comment]
@nickycutesc Thanks for the PR.  Doing a quick review.

**Comment by moxiegirl** [comment]
@nickycutesc The git information in this file is pretty old and assumes quite a bit. So, your changes even are environment-specific. I'm going to rewrite the entire section to simply suggest creating a git repo is a possibility and leave it at that.

Thank you for creating this PR and point out the problems.

**Comment by nickycutesc** [comment]
Thanks @moxiegirl for reviewing my PR! Could I collaborate with you to rewrite the git section?

**Comment by moxiegirl** [comment]
@nickycutesc Git is its own product and its use varies significantly depending on the user's OS and how it is set up (some users use a command line and others use one of many clients), maintaining doc in our product about how to use Git is not appropriate. It is better to refer people to Git documentation which will be both more extensive and formerly maintained.

 Happy to collaborate on something specific to Blockstack tech if you have suggestions there.

**Comment by nickycutesc** [comment]
I’d have to look at the project some more to think of any ideas. What are some of the most pressing issues affecting Blockstack thus far?

**Pull request closed without merging**
