### PR TITLE
Check and review IOS application

### PR DESCRIPTION
**Pull request by moxiegirl**
This pull request includes my working check of the IOS hello-world plus @shreyasthiagaraj 's changes to my check.

### CODE REVIEW

**Comment by moxiegirl** [comment]
@shreyasthiagaraj I've updated the content to reflect the new Swift...but I am still getting this error:

```
UI update SIGNED_OUT
2019-11-06 19:30:19.426197-0800 hello-blockstack-ios[18972:705349] -[hello_blockstack_ios.ViewController signinButton:forEvent:]: unrecognized selector sent to instance 0x7f9b6c101130
2019-11-06 19:30:19.430994-0800 hello-blockstack-ios[18972:705349] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[hello_blockstack_ios.ViewController signinButton:forEvent:]: unrecognized selector sent to instance 0x7f9b6c101130'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00007fff4787df59 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	5   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x00007fff47850e1a -[UIApplication sendAction:to:from:forEvent:] + 83
	7   UIKitCore                           0x00007fff4722ac42 -[UIControl sendAction:to:forEvent:] + 223
	8   UIKitCore                           0x00007fff4722af8c -[UIControl _sendActionsForEvents:withEvent:] + 398
	9   UIKitCore                           0x00007fff47229eeb -[UIControl touchesEnded:withEvent:] + 481
	10  UIKitCore                           0x00007fff4788bc3d -[UIWindow _sendTouchesForEvent:] + 2604
	11  UIKitCore                           0x00007fff4788d544 -[UIWindow sendEvent:] + 4596
	12  UIKitCore                           0x00007fff47868447 -[UIApplication sendEvent:] + 356
	13  UIKit                               0x000000010d23e2b4 -[UIApplicationAccessibility sendEvent:] + 85
	14  UIKitCore                           0x00007fff478e989e __dispatchPreprocessedEventFromEventQueue + 6847
	15  UIKitCore                           0x00007fff478ec364 __handleEventQueueInternal + 5980
	16  UIKitCore                           0x00007fff478ec757 __handleEventQueueInternal + 6991
	17  CoreFoundation                      0x00007fff23bb2221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	18  CoreFoundation                      0x00007fff23bb214c __CFRunLoopDoSource0 + 76
	19  CoreFoundation                      0x00007fff23bb197c __CFRunLoopDoSources0 + 268
	20  CoreFoundation                      0x00007fff23bac62f __CFRunLoopRun + 1263
	21  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	22  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	23  UIKitCore                           0x00007fff4784fb68 UIApplicationMain + 1621
	24  hello-blockstack-ios                0x000000010a8af33b main + 75
	25  libdyld.dylib                       0x00007fff51a1dc25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I've done debugging around this but it doesn't look like a selector problem.  I could use another set of eyes. I'll send you my project.

**Comment by moxiegirl** [comment]
[project.zip](https://github.com/blockstack/docs.blockstack/files/3817767/project.zip)

**Comment by moxiegirl** [comment]
@shreyasthiagaraj Still would like your input why this is getting unrecognized selector.  Talked to Diwarker about this situation; the error only appears at the last and could be related to the version I am running. We will merge this as is as it does contain significant updates.

**Comment by shreyasthiagaraj** [comment]
Hey @moxiegirl oops--I didn't get an email/notif about this and just saw your posts. Sorry! This kind of error usually appears when some UI element had its click functionality removed and was re-assigned to some other functionality without having that original hook also removed. So the system tries to invoke the original method which no longer exists. Let me confirm.

**Comment by shreyasthiagaraj** [comment]
@moxiegirl I can confirm that the issue is an improperly assigned tap action. The `signIn` button, when tapped, calls `signInButton(_ sender: UIButton)`, but the method that exists in the .swift file is just `signIn(_ sender: UIButton)`.

**Comment by shreyasthiagaraj** [comment]
Also, I checked the tutorial and what you have on there is correct. Folks that follow it should not have this issue.

**Comment by moxiegirl** [comment]
@shreyasthiagaraj Thanks! I've corrected the capitalization in the example in text.

**Pull request merged**
