### PR TITLE
Simplification of repo & navigation

### PR DESCRIPTION
**Pull request by johndmulhausen**
- Multiple unused/obsolete pages removed
- Hundreds of .svn files removed
- One left-nav, no more silos
- One "layout" file, not 10 
- GitHub links point to docs repo
- No more collections. URL = File Path
- Multiple improvements from Mark (still in flight)
- Just one reference section, thanks
- Static assets that are not used removed: 

./develop/images/westeros.jpg
./develop/images/confirm-install-command-line-tools-mac-os-x.jpg
./develop/images/install-command-line-tools-os-x.jpg
./develop/images/history-cloud.jpg
./org/images/wallet_sequence.jpg
./community/images/dark.jpg
./community/images/business-camera-coff.jpg
./community/images/appsumo.jpg
./develop/images/kingdom-choices.gif
./develop/images/netlify-deploy.gif
./develop/images/netlify-account.gif
./develop/images/kingdom-subjects.gif
./ios/images/view-editors.gif
./assets/js/switcher.js
./assets/js/custom.js
./assets/navgoco/jquery.navgoco.min.js
./assets/navgoco/jquery.cookie.min.js

### CODE REVIEW

**Comment by markmhx** [comment]
@johndmulhausen Are your changes here still WIP?

**Comment by jeffdomke** [comment]
This is great! 

- Homepage: Suggest we rethink the buckets or main users/scenarios and ask @jasperjansz for some design help.
- Curious to understand the new Connect update in this context – I'm assuming Get Started and Connect will merge? 
- `Get started > Storage` seems to have some overlap with the `Data Storage` section. Am I right that it feels like that section is mostly theory + reference? In that case, feels like it could be edited down quite a bit. 
- `Hubs and user choice` remove as no longer exposed to users in Connect?
- `Data sharing and collaboration` – Maybe should be `Data Indexing` or `Index App Data`.
- I imagine the `Atlas` and `Naming Services` could be combined.
- Suggest remove the entire section `Blockstack and Stacks Tokens`
- Suggest remove Glossary
- Suggest remove `DApp Developer FAQs`

**Comment by johndmulhausen** [comment]
> @johndmulhausen Are your changes here still WIP?

@markmhx I think the changes in here are shippable since they're basically just under-the-hood and re-organizing what the user sees. But, let's try and get @jeffdomke 's feedback addressed before we merge

**Comment by markmhx** [comment]
Note that https://github.com/blockstack/docs.blockstack/pull/616 builds atop this PR for the general release of Blockstack Connect.

**Comment by markmhx** [comment]
Per @jeffdomke's comments:

> Homepage: Suggest we rethink the buckets or main users/scenarios and ask @jasperjansz for some design help.

I agree, though I recommend redesign the homepage separately from this PR since it's a larger consideration.

> Curious to understand the new Connect update in this context – I'm assuming Get Started and Connect will merge? @markmhx

With https://github.com/blockstack/docs.blockstack/pull/616, the "Get started" section has been removed completely with the remaining tutorial ("Todo list") going under the new "Authentication" section and the other Connect pages going under either that section as well or "Smart Contracts".

> Get started > Storage seems to have some overlap with the Data Storage section. Am I right that it feels like that section is mostly theory + reference? In that case, feels like it could be edited down quite a bit.

"Get started > Storage" has been removed entirely with the same PR linked above.

> Hubs and user choice remove as no longer exposed to users in Connect?

Done in the above PR ✅ 

> Data sharing and collaboration – Maybe should be Data Indexing or Index App Data.

Changed to "Data Indexing" in above PR ✅ 

> I imagine the Atlas and Naming Services could be combined.

I'll leave this to @johndmulhausen for a subsequent PR since while I agree they could be combined conceptually, the "Naming Services" menu is already quite long. So we may want to trim first / while merging, which is a larger consideration.

> Suggest remove the entire section Blockstack and Stacks Tokens

This may require some surgery instead of a bulk delete, since it includes Stacks Wallet documentation we may need until mainnet at least. I'll leave to @johndmulhausen for a separate PR.

> Suggest remove Glossary
> Suggest remove DApp Developer FAQs

I've removed the "DApp Developer FAQs" in the above PR ✅  but left the "Glossary" since I suspect @johndmulhausen may want to salvage content from here.

**Comment by markmhx** [comment]
@hstove assigning this to you for help merging into master and deployment whenever you have a chance

**Pull request merged**
